name: Auto merge dependabot pull requests
# Dependabotが作成したPRのうち、GitHub Actionsの更新またはパッチバージョンの更新を自動でマージする

on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - main

jobs:
  call:
    uses: ryoooosk/reusable-workflows/.github/workflows/dependabot-auto-merge.yml@main
    permissions:
      contents: write
      pull-requests: write
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}