name: GitHub Actions lint
# GitHub Actionsのワークフロー定義ファイルの文法チェックを行う

on:
  pull_request:
    paths: 
      - ".github/workflows/*yml"
      - ".github/workflows/*yaml"

# パイプ処理中のエラーをキャッチするために明示的にシェル指定
defaults:
  run:
    shell: bash

# 多重起動の防止
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  call:
    uses: ryoooosk/reusable-workflows/.github/workflows/github-actions-lint.yml@main
