name: Pull Request Lead Time
# Four keys metricsの変更のリードタイムに基づき、PRのファーストコミットからマージまでの時間を計測する。

on:
  pull_request:
    branches:
      - main
    types:
      - closed

      
jobs:
  call:
    uses: ryoooosk/reusable-workflows/.github/workflows/pull-request-lead-time.yml@main
    permissions:
      pull-requests: write
      contents: read
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
