name: Secret scan

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  call:
    uses: ryoooosk/reusable-workflows/.github/workflows/secret-scan.yml@main