name: Secret scan

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: secret lint
        run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" \
          secretlint/secretlint secretlint --maskSecrets '**/*'