name: Text lint

on:
  pull_request:
    paths: 
      - "**/*.md"
      - ".github/workflows/**"
      - "package.json"
      - "package-lock.json"
      - "!**/CLAUDE.md"

  workflow_dispatch:

jobs:
  textlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm install
      - run: npm run lint