name: Text lint

on:
  pull_request:
    paths: 
      - "**/*.md"
      - ".github/workflows/**"
      - "package.json"
      - "package-lock.json"
      - "!**/CLAUDE.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  textlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run textlint
        run: npm run lint